name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3,9,15,21 * * *

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: ryuanerin/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          DONE_BLOCK: '█'
          EMPTY_BLOCK: ' '
